/**
 * Equipment catalog schema — the bundled PF1e equipment database scraped
 * from aonprd.com (Archives of Nethys; OGL content, see LICENSES/NOTICE.md).
 * Data files live in src/data/equipment/*.json, generated by
 * scripts/scrape-equipment/ (dev-time only; committed JSON is the artifact).
 * Pure types — no obsidian imports.
 */
import type { Modifier } from "../calc/modifiers";

/** Mundane base weapon (Weapons.aspx grids + per-item display pages). */
export interface BaseWeaponDef {
  /** slugified name, e.g. "battle-aspergillum" */
  id: string;
  name: string;
  /** gp per unit; sp/cp costs are converted (fractional gp) */
  costGp: number;
  /** damage dice for Small / Medium wielders, "" when none (e.g. net) */
  dmgS: string;
  dmgM: string;
  /** "20", "19-20", "18-20"... "" when the weapon cannot crit */
  critRange: string;
  /** "2", "3", "4"... "" when the weapon cannot crit */
  critMult: string;
  /** range increment in feet; null for pure melee */
  rangeFt: number | null;
  weightLbs: number;
  /** "S", "P", "B and P", "P or S"... as printed */
  dmgType: string;
  /** special qualities as printed: "trip", "reach", "nonlethal"... */
  special: string[];
  proficiency: "simple" | "martial" | "exotic" | "ammo";
  category: "light" | "one-handed" | "two-handed" | "ranged" | "ammunition";
  /** first listed source book, e.g. "Ultimate Equipment" */
  source: string;
}

/** Mundane armor or shield (EquipmentArmor.aspx grids + display pages). */
export interface BaseArmorDef {
  id: string;
  name: string;
  costGp: number;
  /** armor or shield bonus to AC (the typed modifier value before enhancement) */
  acBonus: number;
  kind: "armor" | "shield";
  /** null = unlimited ("—" on AoN) */
  maxDex: number | null;
  /** armor check penalty (0 or negative) */
  acp: number;
  /** arcane spell failure, percent */
  asfPct: number;
  /** speed for a 30 ft. base; null when unaffected */
  speed30: number | null;
  weightLbs: number;
  category: "light" | "medium" | "heavy" | "shield";
  source: string;
}

/**
 * Magic weapon/armor special ability (Flaming, Keen, Fortification...).
 * Priced either as an effective-bonus equivalent or a flat gp adder.
 */
export interface ItemAbilityDef {
  id: string;
  name: string;
  /** "weapon" = both melee and ranged; "armor-or-shield" = both lists */
  appliesTo:
    | "weapon"
    | "melee"
    | "ranged"
    | "armor"
    | "shield"
    | "armor-or-shield";
  /** +N effective bonus cost; null when flat-priced */
  bonusEquivalent: number | null;
  /** flat gp adder; null when bonus-equivalent priced */
  flatPriceGp: number | null;
  casterLevel: number;
  aura: string;
  shortDesc: string;
  source: string;
  /**
   * Numeric-situational abilities only (Bane-style conditional modifiers).
   * Text-only abilities (Flaming, Keen) carry no modifiers — their effect
   * rides the forged item's note instead (see src/calc/forge.ts).
   */
  modifiers?: Modifier[];
}

/** Wondrous item / ring / rod catalog entry. */
export interface MagicItemDef {
  id: string;
  name: string;
  group: "wondrous" | "ring" | "rod";
  /** body slot ("belt", "ring", "none"...) as printed */
  slot: string;
  priceGp: number;
  weightLbs: number;
  casterLevel: number;
  aura: string;
  source: string;
  /** description capped at scrape time (~280 chars) */
  shortDesc: string;
  /** heuristic-derived typed bonuses (src/data/equipment/derive-modifiers.ts) */
  modifiers: Modifier[];
  /** true when the heuristic parser produced no modifiers — user adds manually */
  needsReview?: boolean;
}
