// Generates src/data/icons/registry.ts from:
//   1. assets/icons/rpgawesome-webfont.svg — the RPG Awesome icon font
//      (495 glyphs; icons originally from game-icons.net, CC BY 3.0).
//      Font glyphs are y-up, so each entry carries a baked y-flip transform.
//   2. assets/icons/legacy/*.svg — the 10 original MiniSheet toggle icons
//      (plain 512x512 y-down SVGs, no transform).
// Run: bun run gen:icons   (output is committed)
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const iconsDir = path.join(root, "assets", "icons");
const outDir = path.join(root, "src", "data", "icons");

const entries = new Map(); // id -> { name, viewBox, path, transform? }

const humanize = (slug) =>
  slug
    .split("-")
    .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w))
    .join(" ");

// --- 1. RPG Awesome webfont glyphs -----------------------------------------
const font = readFileSync(path.join(iconsDir, "rpgawesome-webfont.svg"), "utf8");
const face = font.match(/<font-face\s+([^/>]*)\/>/);
const faceAttr = (k) => Number(face?.[1].match(new RegExp(`${k}="(-?\\d+)"`))?.[1]);
const unitsPerEm = faceAttr("units-per-em") || 1024;
const ascent = faceAttr("ascent") || unitsPerEm;
const glyphTransform = `translate(0 ${ascent}) scale(1 -1)`;

let glyphCount = 0;
let skipped = 0;
for (const m of font.matchAll(/<glyph\s+([^>]*?)\/>/g)) {
  const attrs = m[1];
  const get = (k) => attrs.match(new RegExp(`${k}="([^"]*)"`))?.[1];
  const name = get("glyph-name");
  const d = get("d");
  if (!name || !d) {
    skipped++; // space / missing-glyph entries
    continue;
  }
  const id = `ra-${name}`;
  if (entries.has(id)) {
    console.warn(`duplicate glyph id ${id} — keeping first`);
    continue;
  }
  const advX = Number(get("horiz-adv-x")) || unitsPerEm;
  entries.set(id, {
    name: humanize(name),
    viewBox: `0 0 ${advX} ${unitsPerEm}`,
    path: d,
    transform: glyphTransform,
  });
  glyphCount++;
}

// --- 2. Legacy MiniSheet toggle icons ---------------------------------------
let legacyCount = 0;
for (const file of readdirSync(path.join(iconsDir, "legacy")).sort()) {
  if (!file.endsWith(".svg")) continue;
  const svg = readFileSync(path.join(iconsDir, "legacy", file), "utf8");
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  const d = svg.match(/<path d="([^"]+)"/)?.[1];
  if (!viewBox || !d) {
    console.error(`UNPARSEABLE legacy icon: ${file}`);
    process.exitCode = 1;
    continue;
  }
  const stem = file.replace(/\.svg$/, "");
  entries.set(`legacy-${stem}`, { name: `${humanize(stem)} (Legacy)`, viewBox, path: d });
  legacyCount++;
}

// --- emit -------------------------------------------------------------------
const lines = [...entries.entries()].map(([id, e]) => {
  const t = e.transform ? `, transform: ${JSON.stringify(e.transform)}` : "";
  return `  ${JSON.stringify(id)}: { name: ${JSON.stringify(e.name)}, viewBox: ${JSON.stringify(e.viewBox)}, path: ${JSON.stringify(e.path)}${t} },`;
});

const out = `// GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Sources: RPG Awesome webfont (icons by game-icons.net contributors, CC BY 3.0;
// font packaging by Daniela Howe, BSD) + MiniSheet legacy toggle icons.
// See LICENSES/NOTICE.md for attribution.

export interface IconDef {
  name: string;
  viewBox: string;
  path: string;
  /** present for font-derived glyphs (y-up coordinates) */
  transform?: string;
}

export const ICONS: Record<string, IconDef> = {
${lines.join("\n")}
};

export const ICON_IDS: string[] = Object.keys(ICONS);
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(path.join(outDir, "registry.ts"), out);
console.log(
  `registry.ts written: ${glyphCount} rpg-awesome + ${legacyCount} legacy icons` +
    ` (${skipped} empty glyphs skipped; units ${unitsPerEm}, ascent ${ascent})`
);
